FROM nvidia/cuda:10.1-base
MAINTAINER Luisa Zintgraf

RUN apt-get update && apt-get install -y \
    vim wget unzip \
    libosmesa6-dev libgl1-mesa-glx libgl1-mesa-dev libglu1-mesa-dev libxi6 patchelf libglfw3 build-essential

RUN useradd -u <<UID>> --create-home user
USER user
WORKDIR /home/user

RUN wget -q https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh && \
    bash Miniconda3-latest-Linux-x86_64.sh -b -p miniconda3 && \
    rm Miniconda3-latest-Linux-x86_64.sh

ENV PATH /home/user/miniconda3/bin:$PATH

# Python packages
RUN conda install python=3.8 pytorch==1.4 torchvision tensorboard==2.0.0 cudatoolkit=10.1 seaborn snakeviz matplotlib -c pytorch

# MuJoCo
ENV MUJOCO_PY_MJKEY_PATH /home/user/.mujoco/mjkey.txt
ENV MUJOCO_PY_MJPRO_PATH /home/user/.mujoco/mjpro131
RUN mkdir -p .mujoco \
    && wget https://www.roboti.us/download/mjpro131_linux.zip -O mujoco.zip \
    && unzip mujoco.zip -d .mujoco \
    && rm mujoco.zip
COPY mjkey.txt .mujoco/mjkey.txt
ENV LD_LIBRARY_PATH /home/user/.mujoco/mjpro131/bin:${LD_LIBRARY_PATH}

RUN pip install tensorboardX mujoco-py==0.5.7 gym==0.9.1 gym[mujoco]==0.9.1

ADD . /home/user/
